DROP TABLE IF EXISTS Snack;
DROP TABLE IF EXISTS Ticket;
DROP TABLE IF EXISTS Sale;
DROP TABLE IF EXISTS Plays;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Movie;
DROP TABLE IF EXISTS Customer;
DROP TABLE IF EXISTS Cinema;